<?php

/**
 * Default Site Content keys (Arabic + English). Sync via dashboard → Site Content → "Seed default keys".
 *
 * @return list<array{group:string,key:string,value_ar:string,value_en:string}>
 */
return [
    ['group' => 'nav', 'key' => 'nav.home', 'value_ar' => 'الرئيسية', 'value_en' => 'Home'],
    ['group' => 'nav', 'key' => 'nav.about', 'value_ar' => 'عن الشركة', 'value_en' => 'About'],
    ['group' => 'nav', 'key' => 'nav.services', 'value_ar' => 'الخدمات', 'value_en' => 'Services'],
    ['group' => 'nav', 'key' => 'nav.gallery', 'value_ar' => 'المعرض', 'value_en' => 'Gallery'],
    ['group' => 'nav', 'key' => 'nav.process', 'value_ar' => 'طريقة العمل', 'value_en' => 'Process'],
    ['group' => 'nav', 'key' => 'nav.engineers', 'value_ar' => 'للمهندسين', 'value_en' => 'Engineers'],
    ['group' => 'nav', 'key' => 'nav.contact', 'value_ar' => 'تواصل', 'value_en' => 'Contact'],
    ['group' => 'footer', 'key' => 'footer.tagline', 'value_ar' => 'مطابخ فاخرة', 'value_en' => 'Premium kitchens • Built to assemble'],

    ['group' => 'home', 'key' => 'home.meta.title', 'value_ar' => 'الرئيسية', 'value_en' => 'Home'],

    ['group' => 'home', 'key' => 'home.brands.title', 'value_ar' => 'براندات وشركاء نثق فيهم', 'value_en' => 'Trusted brands and partners'],
    ['group' => 'home', 'key' => 'home.brands.subtitle', 'value_ar' => 'نستخدم مكونات وخامات من موردين معتمدين عشان التشطيب يفضل ثابت مع الوقت.', 'value_en' => 'We use components and materials from trusted suppliers so the finish stays consistent over time.'],
    ['group' => 'home', 'key' => 'home.services.title', 'value_ar' => 'خدماتنا', 'value_en' => 'Our Services'],
    ['group' => 'home', 'key' => 'home.services.lead', 'value_ar' => 'تصميم وتصنيع وتركيب بخطوات واضحة، مع خامات مختارة وتشطيب', 'value_en' => 'Design • Build • Install — curated materials & premium finish.'],
    ['group' => 'home', 'key' => 'home.services.leadHighlight', 'value_ar' => 'يليق بالذوق الراقي', 'value_en' => ''],
    ['group' => 'home', 'key' => 'home.services.subline', 'value_ar' => 'تصميم • تصنيع • تركيب — خامات مختارة وتشطيب فاخر.', 'value_en' => 'Design • Build • Install — curated materials & premium finish.'],
    ['group' => 'home', 'key' => 'home.services.cta', 'value_ar' => 'عرض تفاصيل الخدمات', 'value_en' => 'View Service Details'],

    ['group' => 'home', 'key' => 'home.hero.badge', 'value_ar' => 'تصميم وتنفيذ مطابخ فاخرة', 'value_en' => 'Premium Kitchen Design & Build'],
    ['group' => 'home', 'key' => 'home.hero.ctaPrimary', 'value_ar' => 'اطلب تصميم مبدئي', 'value_en' => 'Request a design draft'],
    ['group' => 'home', 'key' => 'home.hero.ctaQuick', 'value_ar' => 'نموذج سريع', 'value_en' => 'Quick form'],
    ['group' => 'home', 'key' => 'home.hero.ctaGallery', 'value_ar' => 'شوف معرض الأعمال', 'value_en' => 'View portfolio'],
    ['group' => 'home', 'key' => 'home.hero.ariaPrev', 'value_ar' => 'الشريحة السابقة', 'value_en' => 'Previous slide'],
    ['group' => 'home', 'key' => 'home.hero.ariaNext', 'value_ar' => 'الشريحة التالية', 'value_en' => 'Next slide'],
    ['group' => 'home', 'key' => 'home.hero.dotsAria', 'value_ar' => 'شرائح الهيرو', 'value_en' => 'Hero slides'],
    ['group' => 'home', 'key' => 'home.hero.slidePrefix', 'value_ar' => 'شريحة', 'value_en' => 'Slide'],
    ['group' => 'home', 'key' => 'home.hero.slideOf', 'value_ar' => 'من', 'value_en' => 'of'],

    ['group' => 'home', 'key' => 'home.kitchens.title', 'value_ar' => 'استكشف تصاميم مطابخنا', 'value_en' => 'Explore our kitchen designs'],
    ['group' => 'home', 'key' => 'home.kitchens.subtitle', 'value_ar' => 'صور حقيقية تعكس جودة التنفيذ، تنوع الستايلات، ولمسة التشطيب النهائية.', 'value_en' => 'Real photos that reflect build quality, style variety, and finishing.'],
    ['group' => 'home', 'key' => 'home.kitchens.fallbackTitle', 'value_ar' => 'Kitchen Project', 'value_en' => 'Kitchen Project'],
    ['group' => 'home', 'key' => 'home.kitchens.fallbackSubtitle', 'value_ar' => 'Modern / Top sellers', 'value_en' => 'Modern / Top sellers'],

    ['group' => 'home', 'key' => 'home.engineers.badge', 'value_ar' => 'مهندسون ومقاولون', 'value_en' => 'Engineers & contractors'],
    ['group' => 'home', 'key' => 'home.engineers.title', 'value_ar' => 'للمهندسين عندنا', 'value_en' => 'For engineers'],
    ['group' => 'home', 'key' => 'home.engineers.lead', 'value_ar' => 'تنسيق قبل التصنيع، مقاسات دقيقة، وتنفيذ مطابق للمخططات — بمستوى تشطيب', 'value_en' => ''],
    ['group' => 'home', 'key' => 'home.engineers.leadHighlight', 'value_ar' => 'فخم وواضح', 'value_en' => ''],
    ['group' => 'home', 'key' => 'home.engineers.subtitle', 'value_ar' => 'تنسيق • مواصفات دقيقة • تسليم موثوق في الموقع.', 'value_en' => 'Coordination • specs • on-site delivery you can trust.'],
    ['group' => 'home', 'key' => 'home.engineers.ctaPage', 'value_ar' => 'صفحة المهندسين', 'value_en' => 'Engineers page'],
    ['group' => 'home', 'key' => 'home.engineers.ctaContact', 'value_ar' => 'تواصل معنا', 'value_en' => 'Contact us'],

    ['group' => 'home', 'key' => 'home.premium.badge', 'value_ar' => 'For Premium Clients', 'value_en' => 'For Premium Clients'],
    ['group' => 'home', 'key' => 'home.premium.title', 'value_ar' => "تشطيب يليق\nبالطبقة الراقية", 'value_en' => "Finishing that fits\na refined clientele"],
    ['group' => 'home', 'key' => 'home.premium.imageAlt', 'value_ar' => 'Kitchen detail', 'value_en' => 'Kitchen detail'],

    ['group' => 'home', 'key' => 'home.process.title', 'value_ar' => "من الفكرة\nللتنفيذ الكامل", 'value_en' => "From concept\nto full delivery"],
    ['group' => 'home', 'key' => 'home.process.body', 'value_ar' => 'بنشتغل بخطوات واضحة: مقاسات دقيقة، تصميم مقترح، تصنيع منظم، وتسليم نهائي بمستوى جودة ثابت.', 'value_en' => 'Clear steps: accurate measurements, proposed design, organized manufacturing, and final handover with consistent quality.'],
    ['group' => 'home', 'key' => 'home.process.step.measure', 'value_ar' => 'قياس', 'value_en' => 'Measure'],
    ['group' => 'home', 'key' => 'home.process.step.design', 'value_ar' => 'تصميم', 'value_en' => 'Design'],
    ['group' => 'home', 'key' => 'home.process.step.build', 'value_ar' => 'تصنيع', 'value_en' => 'Build'],
    ['group' => 'home', 'key' => 'home.process.step.install', 'value_ar' => 'تركيب', 'value_en' => 'Install'],
    ['group' => 'home', 'key' => 'home.process.cta', 'value_ar' => 'شوف طريقة العمل', 'value_en' => 'See how we work'],

    ['group' => 'home', 'key' => 'home.contact.title', 'value_ar' => 'تواصل معنا', 'value_en' => 'Contact Us'],
    ['group' => 'home', 'key' => 'home.contact.lead', 'value_ar' => 'املأ البيانات التالية وسيفتح واتساب برسالة جاهزة.', 'value_en' => 'Fill in the fields and WhatsApp will open with a prefilled message.'],
    ['group' => 'home', 'key' => 'home.contact.leadHighlight', 'value_ar' => 'أسرع رد', 'value_en' => 'Faster reply'],
    ['group' => 'home', 'key' => 'home.contact.leadEnd', 'value_ar' => 'للاستفسار والتصميم المبدئي.', 'value_en' => 'for questions and a first design pass.'],
    ['group' => 'home', 'key' => 'home.contact.subline', 'value_ar' => 'تواصل سريع — نفس خطوات صفحة التواصل الكاملة.', 'value_en' => 'Quick contact — same flow as the full contact page.'],
    ['group' => 'home', 'key' => 'home.contact.intro', 'value_ar' => 'نركّز على مطابخ مودرن فخمة للأفراد والمهندسين، بخطوات واضحة من القياس حتى التسليم.', 'value_en' => 'Modern luxury kitchens for homeowners and engineers — clear steps from measure to handover.'],
    ['group' => 'home', 'key' => 'home.contact.fullPageLink', 'value_ar' => 'صفحة التواصل الكاملة ←', 'value_en' => 'Full contact page ←'],

    ['group' => 'home', 'key' => 'home.contact.form.nameLabel', 'value_ar' => 'اسمك', 'value_en' => 'Your name'],
    ['group' => 'home', 'key' => 'home.contact.form.namePlaceholder', 'value_ar' => 'اكتب اسمك', 'value_en' => 'Your name'],
    ['group' => 'home', 'key' => 'home.contact.form.propertyLabel', 'value_ar' => 'نوع العقار', 'value_en' => 'Property type'],
    ['group' => 'home', 'key' => 'home.contact.property.apt', 'value_ar' => 'شقة', 'value_en' => 'Apartment'],
    ['group' => 'home', 'key' => 'home.contact.property.villa', 'value_ar' => 'فيلا', 'value_en' => 'Villa'],
    ['group' => 'home', 'key' => 'home.contact.property.any', 'value_ar' => 'أي مشروع', 'value_en' => 'Any project'],
    ['group' => 'home', 'key' => 'home.contact.form.areaLabel', 'value_ar' => 'المقاس/المساحة (اختياري)', 'value_en' => 'Size / area (optional)'],
    ['group' => 'home', 'key' => 'home.contact.form.areaPlaceholder', 'value_ar' => 'مثال: 4x3 / عدد قطع', 'value_en' => 'e.g. 4x3 m'],
    ['group' => 'home', 'key' => 'home.contact.form.detailsLabel', 'value_ar' => 'تفاصيل سريعة (اختياري)', 'value_en' => 'Quick details (optional)'],
    ['group' => 'home', 'key' => 'home.contact.form.detailsPlaceholder', 'value_ar' => 'ذوقك؟ خامة؟ توقيت التنفيذ؟', 'value_en' => 'Style? Materials? Timeline?'],
    ['group' => 'home', 'key' => 'home.contact.submit', 'value_ar' => 'ارسل على واتساب', 'value_en' => 'Send on WhatsApp'],
    ['group' => 'home', 'key' => 'home.contact.submitDisabled', 'value_ar' => 'حدّد رقم واتساب من إعدادات الموقع في لوحة التحكم.', 'value_en' => 'Set the WhatsApp number under Site configuration in the dashboard.'],
    ['group' => 'home', 'key' => 'home.contact.formHint', 'value_ar' => 'رسالة جاهزة — يفتح واتساب.', 'value_en' => 'Prefilled message — opens WhatsApp.'],

    ['group' => 'home', 'key' => 'home.contact.waNameFallback', 'value_ar' => 'عميل', 'value_en' => 'Client'],
    ['group' => 'home', 'key' => 'home.contact.waAreaFallback', 'value_ar' => 'حسب المساحة', 'value_en' => 'Per area'],
    ['group' => 'home', 'key' => 'home.contact.waClosing', 'value_ar' => 'أريد تصميم وتنفيذ مطبخ مودرن فخم.', 'value_en' => 'I want a modern luxury kitchen design & build.'],
    ['group' => 'home', 'key' => 'home.contact.waHi', 'value_ar' => 'مرحبًا، أنا', 'value_en' => 'Hi, I am'],
    ['group' => 'home', 'key' => 'home.contact.waProject', 'value_ar' => 'نوع المشروع', 'value_en' => 'Project type'],
    ['group' => 'home', 'key' => 'home.contact.waArea', 'value_ar' => 'المقاس/المساحة', 'value_en' => 'Size / area'],
    ['group' => 'home', 'key' => 'home.contact.waDetailsPrefix', 'value_ar' => 'تفاصيل', 'value_en' => 'Details'],
    ['group' => 'home', 'key' => 'home.contact.form.phoneLabel', 'value_ar' => 'رقم الموبايل', 'value_en' => 'Mobile number'],
    ['group' => 'home', 'key' => 'home.contact.form.phonePlaceholder', 'value_ar' => '01xxxxxxxxx', 'value_en' => '01xxxxxxxxx'],
    ['group' => 'home', 'key' => 'home.contact.form.emailLabel', 'value_ar' => 'البريد الإلكتروني (اختياري)', 'value_en' => 'Email (optional)'],
    ['group' => 'home', 'key' => 'home.contact.form.emailPlaceholder', 'value_ar' => 'name@example.com', 'value_en' => 'name@example.com'],
    ['group' => 'home', 'key' => 'home.contact.waPhoneLine', 'value_ar' => 'جوال', 'value_en' => 'Mobile'],
    ['group' => 'home', 'key' => 'home.contact.waEmailLine', 'value_ar' => 'البريد', 'value_en' => 'Email'],
    ['group' => 'home', 'key' => 'home.contact.submitRequest', 'value_ar' => 'إرسال الطلب', 'value_en' => 'Send request'],
    ['group' => 'home', 'key' => 'home.contact.submitSuccess', 'value_ar' => 'تم استلام طلبك بنجاح.', 'value_en' => 'Your request was received.'],

    ['group' => 'home', 'key' => 'home.footer.about', 'value_ar' => 'مطابخ مودرن فخمة — تصميم وتنفيذ بجودة ثابتة للشقق والفلل والمهندسين.', 'value_en' => 'Modern luxury kitchens — consistent design & build for apartments, villas, and engineers.'],
    ['group' => 'home', 'key' => 'home.footer.quickLinks', 'value_ar' => 'روابط سريعة', 'value_en' => 'Quick links'],
    ['group' => 'home', 'key' => 'home.footer.contactHeading', 'value_ar' => 'تواصل', 'value_en' => 'Contact'],
    ['group' => 'home', 'key' => 'home.footer.contactForm', 'value_ar' => 'نموذج التواصل', 'value_en' => 'Contact form'],
    ['group' => 'home', 'key' => 'home.footer.quickForm', 'value_ar' => 'نموذج سريع (هذه الصفحة)', 'value_en' => 'Quick form (this page)'],
    ['group' => 'home', 'key' => 'home.footer.readyTitle', 'value_ar' => 'جاهز لمطبخ جديد؟', 'value_en' => 'Ready for a new kitchen?'],
    ['group' => 'home', 'key' => 'home.footer.readyBody', 'value_ar' => 'اطلب تصميم مبدئي أو راجع معرض الأعمال.', 'value_en' => 'Request a first design or browse the gallery.'],
    ['group' => 'home', 'key' => 'home.footer.ctaDesign', 'value_ar' => 'اطلب تصميم', 'value_en' => 'Request design'],
    ['group' => 'home', 'key' => 'home.footer.ctaGallery', 'value_ar' => 'المعرض', 'value_en' => 'Gallery'],
    ['group' => 'home', 'key' => 'home.footer.rights', 'value_ar' => 'جميع الحقوق محفوظة.', 'value_en' => 'All rights reserved.'],
    ['group' => 'home', 'key' => 'home.footer.bottomLine', 'value_ar' => 'Premium kitchens • Design & build', 'value_en' => 'Premium kitchens • Design & build'],

    ['group' => 'home', 'key' => 'home.gallery.fallbackEngineerTitle', 'value_ar' => 'مشروع', 'value_en' => 'Project'],
    ['group' => 'home', 'key' => 'home.gallery.fallbackEngineerEn', 'value_ar' => 'Engineering showcase', 'value_en' => 'Engineering showcase'],

    ['group' => 'engineers', 'key' => 'engineers.meta.title', 'value_ar' => 'للمهندسين', 'value_en' => 'Engineers'],
    ['group' => 'engineers', 'key' => 'engineers.hero.imageAlt', 'value_ar' => 'تنفيذ للمهندسين', 'value_en' => 'Build for engineers'],
    ['group' => 'engineers', 'key' => 'engineers.hero.badge', 'value_ar' => 'للمهندسين والمقاولين', 'value_en' => 'For engineers & contractors'],
    ['group' => 'engineers', 'key' => 'engineers.hero.lead', 'value_ar' => 'تنفيذ مطابق للمخططات بمستوى تشطيب فخم—وبتنسيق واضح قبل ما تبدأ التصنيع.', 'value_en' => 'Drawing-accurate execution with premium finish — clear coordination before manufacturing.'],
    ['group' => 'engineers', 'key' => 'engineers.panel.title', 'value_ar' => 'للمهندسين', 'value_en' => 'For engineers'],
    ['group' => 'engineers', 'key' => 'engineers.panel.intro', 'value_ar' => 'نشتغل معاكم على التفاصيل قبل التصنيع، وننفّذ بمقاسات دقيقة ومواعيد واضحة.', 'value_en' => 'We work through details before manufacturing, with accurate dimensions and clear schedules.'],
    ['group' => 'engineers', 'key' => 'engineers.bullet.ar1', 'value_ar' => 'تنسيق قبل التصنيع', 'value_en' => 'Pre-build coordination'],
    ['group' => 'engineers', 'key' => 'engineers.bullet.ar2', 'value_ar' => 'دقة المقاسات والتفاصيل', 'value_en' => 'Precise measurements & details'],
    ['group' => 'engineers', 'key' => 'engineers.bullet.ar3', 'value_ar' => 'تنفيذ مطابق للستايل', 'value_en' => 'On-style execution'],
    ['group' => 'engineers', 'key' => 'engineers.bullet.ar4', 'value_ar' => 'تسليم منظم وبمواعيد', 'value_en' => 'Organized delivery & timelines'],
    ['group' => 'engineers', 'key' => 'engineers.bullet.en1', 'value_ar' => 'Built to spec (drawings & details).', 'value_en' => 'Built to spec (drawings & details).'],
    ['group' => 'engineers', 'key' => 'engineers.bullet.en2', 'value_ar' => 'Precise measurement control.', 'value_en' => 'Precise measurement control.'],
    ['group' => 'engineers', 'key' => 'engineers.bullet.en3', 'value_ar' => 'Clear schedule & organized installation.', 'value_en' => 'Clear schedule & organized installation.'],
    ['group' => 'engineers', 'key' => 'engineers.bullet.en4', 'value_ar' => 'Material coordination before manufacturing.', 'value_en' => 'Material coordination before manufacturing.'],
    ['group' => 'engineers', 'key' => 'engineers.gallery.title', 'value_ar' => 'جودة تنفيذ في الصور', 'value_en' => 'Execution quality in photos'],
    ['group' => 'engineers', 'key' => 'engineers.gallery.subtitle', 'value_ar' => 'لقطات من مشاريع تعكس الالتزام بالمخطط، التشطيب، والتنسيق.', 'value_en' => 'Project shots reflecting drawings, finishing, and coordination.'],
    ['group' => 'engineers', 'key' => 'engineers.gallery.subline', 'value_ar' => 'مشاريع حقيقية — تشطيب وتنسيق واضحين.', 'value_en' => 'Real projects — finish & coordination you can see.'],
    ['group' => 'engineers', 'key' => 'engineers.marquee.title', 'value_ar' => 'معرض متحرك — تفاصيل التنفيذ', 'value_en' => 'Animated strip — execution details'],
    ['group' => 'engineers', 'key' => 'engineers.marquee.hint', 'value_ar' => 'شريط متحرّك — مرّر المؤشر للإيقاف المؤقت', 'value_en' => 'Animated strip — hover to pause'],
    ['group' => 'engineers', 'key' => 'engineers.delivery.title', 'value_ar' => 'تسليم مناسب للمهندسين', 'value_en' => 'Engineer-friendly delivery'],
    ['group' => 'engineers', 'key' => 'engineers.contact.kicker', 'value_ar' => 'تواصل معنا', 'value_en' => 'Contact us'],
    ['group' => 'engineers', 'key' => 'engineers.contact.title', 'value_ar' => 'جاهزين ننسّق مع فريقك قبل التصنيع', 'value_en' => 'Ready to coordinate with your team before manufacturing'],
    ['group' => 'engineers', 'key' => 'engineers.contact.lead', 'value_ar' => 'اطلب مكالمة أو تواصل كتابي — نرجع لك بخطوات واضحة ومقترح تنفيذ.', 'value_en' => 'Request a call or message — we reply with clear steps and an execution plan.'],
    ['group' => 'engineers', 'key' => 'engineers.contact.subline', 'value_ar' => 'تواصل معنا للتنسيق، مراجعة المخططات، وخطة التنفيذ.', 'value_en' => 'Contact us for coordination, drawings review, and execution plan.'],
    ['group' => 'engineers', 'key' => 'engineers.contact.ctaFull', 'value_ar' => 'صفحة التواصل', 'value_en' => 'Contact page'],
    ['group' => 'engineers', 'key' => 'engineers.contact.ctaQuick', 'value_ar' => 'نموذج سريع (الرئيسية)', 'value_en' => 'Quick form (home)'],
    ['group' => 'engineers', 'key' => 'engineers.whatsappPrefix', 'value_ar' => 'واتساب:', 'value_en' => 'WhatsApp:'],

    ['group' => 'process', 'key' => 'process.meta.title', 'value_ar' => 'طريقة العمل', 'value_en' => 'Process'],
    ['group' => 'process', 'key' => 'process.hero.title', 'value_ar' => 'طريقة العمل', 'value_en' => 'Our process'],
    ['group' => 'process', 'key' => 'process.hero.subtitleAr', 'value_ar' => 'خطوات واضحة من القياس حتى التسليم.', 'value_en' => 'Clear steps from measure to handover.'],
    ['group' => 'process', 'key' => 'process.hero.subtitleEn', 'value_ar' => 'عملية مبنية لنتائج فاخرة.', 'value_en' => 'A process built for premium outcomes.'],
    ['group' => 'process', 'key' => 'process.steps.boxTitle', 'value_ar' => 'تنفيذ خطوة بخطوة', 'value_en' => 'Step-by-step build'],
    ['group' => 'process', 'key' => 'process.steps.boxSubline', 'value_ar' => 'قياس • تصميم • تصنيع', 'value_en' => 'Measure • Design • Build'],
    ['group' => 'process', 'key' => 'process.step1.arTitle', 'value_ar' => 'استلام المقاسات', 'value_en' => 'Measurements'],
    ['group' => 'process', 'key' => 'process.step1.enTitle', 'value_ar' => 'Measure', 'value_en' => 'Measure'],
    ['group' => 'process', 'key' => 'process.step1.descAr', 'value_ar' => 'تفاصيل دقيقة للمقاس والزوايا عشان التنفيذ يطلع مظبوط.', 'value_en' => 'Accurate dimensions and angles for correct execution.'],
    ['group' => 'process', 'key' => 'process.step1.descEn', 'value_ar' => 'Exact measurements & angles for perfect execution.', 'value_en' => 'Exact measurements & angles for perfect execution.'],
    ['group' => 'process', 'key' => 'process.step2.arTitle', 'value_ar' => 'تصميم وموديل 3D', 'value_en' => '3D design'],
    ['group' => 'process', 'key' => 'process.step2.enTitle', 'value_ar' => '3D Concept', 'value_en' => '3D Concept'],
    ['group' => 'process', 'key' => 'process.step2.descAr', 'value_ar' => 'نقترح الستايل والخامات قبل ما نبدأ تصنيع أي جزء.', 'value_en' => 'We propose style and materials before manufacturing starts.'],
    ['group' => 'process', 'key' => 'process.step2.descEn', 'value_ar' => 'Pick the style & materials before manufacturing.', 'value_en' => 'Pick the style & materials before manufacturing.'],
    ['group' => 'process', 'key' => 'process.step3.arTitle', 'value_ar' => 'تصنيع وتشطيب وتسليم', 'value_en' => 'Build & handover'],
    ['group' => 'process', 'key' => 'process.step3.enTitle', 'value_ar' => 'Premium Build', 'value_en' => 'Premium Build'],
    ['group' => 'process', 'key' => 'process.step3.descAr', 'value_ar' => 'تشطيب فخم + متابعة تركيب لحد التسليم النهائي.', 'value_en' => 'Premium finishing and installation follow-up to final handover.'],
    ['group' => 'process', 'key' => 'process.step3.descEn', 'value_ar' => 'Premium finishing with on-site completion.', 'value_en' => 'Premium finishing with on-site completion.'],
    ['group' => 'process', 'key' => 'process.bottom.badge', 'value_ar' => 'من الفكرة إلى التسليم', 'value_en' => 'Concept to Delivery'],
    ['group' => 'process', 'key' => 'process.bottom.title', 'value_ar' => 'الجودة بتبان من أول خطوة', 'value_en' => 'Quality shows from step one'],
    ['group' => 'process', 'key' => 'process.bottom.body', 'value_ar' => 'بنشتغل بطريقة منظمة عشان المهندس والعميل يبقوا على نفس الصورة قبل التصنيع.', 'value_en' => 'We work in a structured way so engineers and clients share the same picture before manufacturing.'],
    ['group' => 'process', 'key' => 'process.bottom.cta', 'value_ar' => 'اطلب تصميم مبدئي', 'value_en' => 'Request a design draft'],

    ['group' => 'contact', 'key' => 'contact.meta.title', 'value_ar' => 'تواصل', 'value_en' => 'Contact'],
    ['group' => 'contact', 'key' => 'contact.hero.titleWith', 'value_ar' => 'تواصل مع', 'value_en' => 'Contact'],
    ['group' => 'contact', 'key' => 'contact.hero.lead', 'value_ar' => 'اكتب بياناتك، وسيفتح واتساب برسالة جاهزة.', 'value_en' => 'Enter your details and WhatsApp opens with a prefilled message.'],
    ['group' => 'contact', 'key' => 'contact.hero.leadHighlight', 'value_ar' => 'أسرع تواصل', 'value_en' => 'Faster contact'],
    ['group' => 'contact', 'key' => 'contact.hero.leadEnd', 'value_ar' => 'للطبقة الراقية والمهندسين.', 'value_en' => 'for discerning clients and engineers.'],
    ['group' => 'contact', 'key' => 'contact.card1.title', 'value_ar' => 'تنسيق راقٍ للمشروع', 'value_en' => 'Premium coordination'],
    ['group' => 'contact', 'key' => 'contact.card1.line', 'value_ar' => 'خطوات واضحة وتشطيب فاخر.', 'value_en' => 'Clear steps + premium finish.'],
    ['group' => 'contact', 'key' => 'contact.card2.title', 'value_ar' => 'مناسب للمهندسين', 'value_en' => 'Engineer-friendly'],
    ['group' => 'contact', 'key' => 'contact.card2.line', 'value_ar' => 'تنفيذ يطابق الرسوم ونية التصميم.', 'value_en' => 'Matching execution to design intent.'],
    ['group' => 'contact', 'key' => 'contact.form.areaPlaceholder', 'value_ar' => 'مثال: 4x3 / عدد قطع / مساحة', 'value_en' => 'e.g. 4x3 m / units / area'],
    ['group' => 'contact', 'key' => 'contact.form.detailsPlaceholder', 'value_ar' => 'ذوقك؟ خامة مفضلة؟ توقيت التنفيذ؟', 'value_en' => 'Style? Preferred materials? Timeline?'],
    ['group' => 'contact', 'key' => 'contact.form.submitDisabled', 'value_ar' => 'حدّد رقم واتساب', 'value_en' => 'Set WhatsApp number'],
    ['group' => 'contact', 'key' => 'contact.form.hintLine1', 'value_ar' => 'لا حاجة لخادم خلفي.', 'value_en' => 'No backend needed.'],
    ['group' => 'contact', 'key' => 'contact.form.hintLine2', 'value_ar' => 'الرسالة جاهزة مسبقًا.', 'value_en' => 'Message is prefilled.'],
    ['group' => 'contact', 'key' => 'contact.envWarning', 'value_ar' => 'حدّث VITE_WHATSAPP_NUMBER في ملف .env.', 'value_en' => 'Update VITE_WHATSAPP_NUMBER in your .env file.'],

    ['group' => 'services', 'key' => 'services.page.metaTitle', 'value_ar' => 'الخدمات', 'value_en' => 'Services'],
    ['group' => 'services', 'key' => 'services.page.heroTitle', 'value_ar' => 'خدماتنا', 'value_en' => 'Our Services'],
    ['group' => 'services', 'key' => 'services.page.leadPart1', 'value_ar' => 'تصميم + تصنيع + تركيب مطابخ فخمة، مناسب للشقق والفلل', 'value_en' => 'Design, manufacturing, and installation of luxury kitchens for apartments and villas'],
    ['group' => 'services', 'key' => 'services.page.leadHighlight', 'value_ar' => 'بمستوى مختلف', 'value_en' => 'at a different level'],
    ['group' => 'services', 'key' => 'services.page.leadPart2', 'value_ar' => 'من التفاصيل.', 'value_en' => 'in the details.'],
    ['group' => 'services', 'key' => 'services.page.ctaBadge', 'value_ar' => 'بداية احترافية', 'value_en' => 'Premium Start'],
    ['group' => 'services', 'key' => 'services.page.ctaTitle', 'value_ar' => 'ابدأ بتصميم مبدئي وخطة تنفيذ واضحة', 'value_en' => 'Start with a concept and a clear build plan'],
    ['group' => 'services', 'key' => 'services.page.ctaBody', 'value_ar' => 'نركّز على وضوح الخطوات والتزام بالمقاسات والتفاصيل حتى التسليم.', 'value_en' => 'We focus on clear steps, measurements, and details through handover.'],
    ['group' => 'services', 'key' => 'services.page.ctaButton', 'value_ar' => 'اطلب تواصل الآن', 'value_en' => 'Contact us now'],

    ['group' => 'about', 'key' => 'about.page.metaTitle', 'value_ar' => 'عن الشركة', 'value_en' => 'About'],
    ['group' => 'about', 'key' => 'about.page.heroTitle', 'value_ar' => 'عن شركتنا', 'value_en' => 'About us'],
    ['group' => 'about', 'key' => 'about.page.heroLead', 'value_ar' => 'تصميم وتنفيذ مطابخ فاخرة للشقق والفلل والمهندسين، بخطوات واضحة من القياس حتى التسليم.', 'value_en' => 'Premium kitchen design & build for apartments, villas, and engineers — clear steps from measure to handover.'],
    ['group' => 'about', 'key' => 'about.side.badge', 'value_ar' => 'معايير فاخرة', 'value_en' => 'Luxury standards'],
    ['group' => 'about', 'key' => 'about.side.title', 'value_ar' => 'تصميم • تصنيع • تشطيب', 'value_en' => 'Design • Build • Finish'],
    ['group' => 'about', 'key' => 'about.card1.title', 'value_ar' => 'تشطيب فخم', 'value_en' => 'Premium Finishing'],
    ['group' => 'about', 'key' => 'about.card1.body', 'value_ar' => 'تفاصيل دقيقة وخامات مختارة عشان شكل نهائي يستمر.', 'value_en' => 'Careful details and curated materials for a lasting finish.'],
    ['group' => 'about', 'key' => 'about.card2.title', 'value_ar' => 'تصميم واضح قبل التصنيع', 'value_en' => 'Concept Before Cut'],
    ['group' => 'about', 'key' => 'about.card2.body', 'value_ar' => 'بنجهز تصور يطمنك: ستايل + ألوان + توزيع قبل ما نبدأ تصنيع.', 'value_en' => 'A clear concept: style, colors, and layout before manufacturing.'],
    ['group' => 'about', 'key' => 'about.card3.title', 'value_ar' => 'دقة تنفيذ', 'value_en' => 'Build Precision'],
    ['group' => 'about', 'key' => 'about.card3.body', 'value_ar' => 'تنفيذ مطابق مع المتابعة لحد التسليم النهائي.', 'value_en' => 'Built to match with full follow-up until final delivery.'],
    ['group' => 'about', 'key' => 'about.footer.tagline', 'value_ar' => 'للطبقة الراقية', 'value_en' => 'For premium clients'],
    ['group' => 'about', 'key' => 'about.footer.line', 'value_ar' => 'تصميم يخدم الأفراد والمهندسين.', 'value_en' => 'Designed for discerning individuals & engineers.'],
    ['group' => 'about', 'key' => 'about.footer.cta', 'value_ar' => 'اطلب تواصل الآن', 'value_en' => 'Contact us now'],

    ['group' => 'gallery', 'key' => 'gallery.page.title', 'value_ar' => 'المعرض', 'value_en' => 'Gallery'],
    ['group' => 'gallery', 'key' => 'gallery.page.lead', 'value_ar' => 'استايلات وتشطيبات تناسب الشقق والفلل — مجموعة صور من نماذج مطابخ متنوعة.', 'value_en' => 'Styles and finishes for apartments and villas — a selection of kitchen showcases.'],
    ['group' => 'gallery', 'key' => 'gallery.fallback.project', 'value_ar' => 'مشروع', 'value_en' => 'Project'],
    ['group' => 'gallery', 'key' => 'gallery.fallback.tagline', 'value_ar' => 'مودرن / تشطيب فاخر', 'value_en' => 'Modern / Premium finish'],
];
